import React,{useEffect,useMemo,useState} from "react";
import {BarChart3,Eye,Link2,LogOut,Plus,QrCode,RefreshCw,Shield,Trash2,UserPlus,Users,X,Upload,Pencil} from "lucide-react";
import {supabase} from "./config";
import "./admin-ui.css";
import "./visitor-analytics.css";

const emptyForm={full_name:"",email:"",password:"",title:"",url:"",logo_url:""};
const initialVisitor={total:0,today:0,logged_in:0,guest:0,today_logged_in:0,today_guest:0,unique_sessions:0,today_unique_sessions:0};
const permissionItems=[
 ["dashboard_view","Dashboard & Analytics"],["users_view","View Users"],["users_create","Create Users"],["users_disable","Enable / Disable Users"],["users_delete","Delete Users"],["users_qr","Download Permanent QR"],["links_manage","Manage Important Links"]
];
function permanentQrUrl(pin){return `https://api.qrserver.com/v1/create-qr-code/?size=500x500&data=${encodeURIComponent(pin)}`}
async function downloadPermanentQr(pin){if(!pin)return;const url=permanentQrUrl(pin);try{const r=await fetch(url,{mode:"cors",cache:"no-store"});if(!r.ok)throw new Error("QR download failed");const blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`PrintBhejo-Permanent-QR-${pin}.png`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}catch{window.open(url,"_blank","noopener,noreferrer")}}

export default function AdminPanel({user,profile,onLogout}){
 const isAdmin=profile?.role==="admin";
 const permissions=profile?.permissions||{};
 const can=p=>isAdmin||permissions[p]===true;
 const [profiles,setProfiles]=useState([]),[links,setLinks]=useState([]),[staff,setStaff]=useState([]),[stats,setStats]=useState({users:0,logins:0,transfers:0,todayLogins:0,todayTransfers:0}),[visitor,setVisitor]=useState(initialVisitor);
 const [loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[visitorError,setVisitorError]=useState(""),[modal,setModal]=useState(null),[message,setMessage]=useState(""),[form,setForm]=useState(emptyForm),[logoFile,setLogoFile]=useState(null),[uploadingLogo,setUploadingLogo]=useState(false),[editingLink,setEditingLink]=useState(null),[actionUser,setActionUser]=useState(null),[staffForm,setStaffForm]=useState({full_name:"",email:"",password:"",permissions:{...permissionItems.reduce((a,[k])=>({...a,[k]:false}),{})}}),[editingStaff,setEditingStaff]=useState(null);
 const load=async()=>{if(!supabase)return;setRefreshing(true);try{const start=new Date();start.setHours(0,0,0,0);const profilePromise=can("users_view")?supabase.from("profiles").select("id,full_name,role,disabled,permanent_pin,created_at,last_login_at,permissions").order("created_at",{ascending:false}):Promise.resolve({data:[]});const linkPromise=supabase.from("important_links").select("*").order("created_at",{ascending:false});const statsPromises=can("dashboard_view")?[supabase.from("login_events").select("id",{count:"exact",head:true}),supabase.from("transfer_events").select("id",{count:"exact",head:true}),supabase.from("login_events").select("id",{count:"exact",head:true}).gte("created_at",start.toISOString()),supabase.from("transfer_events").select("id",{count:"exact",head:true}).gte("created_at",start.toISOString()),supabase.rpc("get_visitor_stats")]:[];const [p,l,...sv]=await Promise.all([profilePromise,linkPromise,...statsPromises]);const pd=p.data||[];setProfiles(pd);setLinks(l.data||[]);if(can("dashboard_view")){const [lg,tr,tlg,ttr,v]=sv;setStats({users:pd.filter(x=>x.role==="user").length,logins:lg?.count||0,transfers:tr?.count||0,todayLogins:tlg?.count||0,todayTransfers:ttr?.count||0});if(v?.error)setVisitorError(v.error.message);else{setVisitor({...initialVisitor,...(v?.data||{})});setVisitorError("")}}if(isAdmin){const {data,error}=await supabase.functions.invoke("admin-user-management",{body:{action:"list_staff"}});if(!error&&!data?.error)setStaff(data?.staff||[])} }finally{setRefreshing(false);setLoading(false)}};
 useEffect(()=>{load();const t=setInterval(load,60000);return()=>clearInterval(t)},[]);
 const users=useMemo(()=>profiles.filter(p=>p.role==="user"),[profiles]);
 const resetForm=()=>{setForm(emptyForm);setLogoFile(null);setEditingLink(null)};
 const closeModal=()=>{setModal(null);setMessage("");setActionUser(null);resetForm();setEditingStaff(null);setStaffForm({full_name:"",email:"",password:"",permissions:permissionItems.reduce((a,[k])=>({...a,[k]:false}),{})})};
 async function createUser(e){e.preventDefault();setMessage("");try{const {data,error}=await supabase.functions.invoke("admin-user-management",{body:{action:"create",full_name:form.full_name.trim(),email:form.email.trim(),password:form.password}});if(error)throw new Error(error.message||"User create failed");if(data?.error)throw new Error(data.error);closeModal();await load()}catch(e){setMessage(e.message||"User create failed")}}
 async function toggleUser(p){try{const action=p.disabled?"enable":"disable";const {data,error}=await supabase.functions.invoke("admin-user-management",{body:{action,user_id:p.id}});if(error)throw new Error(error.message||"Could not update user");if(data?.error)throw new Error(data.error);await load()}catch(e){setMessage(e.message||"Could not update user")}}
 async function prepareAndDownloadQr(p){if(!p?.id||actionUser===p.id)return;setActionUser(p.id);setMessage("");try{let pin=p.permanent_pin;if(!pin){const {data,error}=await supabase.functions.invoke("admin-user-management",{body:{action:"ensure_pin",user_id:p.id}});if(error)throw new Error(error.message||"Could not generate permanent QR");if(data?.error)throw new Error(data.error);pin=data?.permanent_pin;await load()}if(!pin)throw new Error("Permanent PIN not available.");await downloadPermanentQr(pin)}catch(e){setMessage(e.message||"Could not download permanent QR")}finally{setActionUser(null)}}
 async function deleteUser(p){if(!p||p.id===user?.id)return;if(!window.confirm(`Delete account for ${p.full_name||"this user"}? This permanently removes the login account.`))return;setActionUser(p.id);setMessage("");try{const {data,error}=await supabase.functions.invoke("admin-user-management",{body:{action:"delete",user_id:p.id}});if(error)throw new Error(error.message||"Could not delete user");if(data?.error)throw new Error(data.error);await load()}catch(e){setMessage(e.message||"Could not delete user")}finally{setActionUser(null)}}
 async function saveLink(e){e.preventDefault();setMessage("");if(!form.title.trim()||!form.url.trim()){setMessage("Link name and website URL are required.");return}try{let logoUrl=form.logo_url.trim()||null;if(logoFile){setUploadingLogo(true);const ext=(logoFile.name.split(".").pop()||"png").toLowerCase().replace(/[^a-z0-9]/g,"");const path=`links/${crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from("admin-assets").upload(path,logoFile,{contentType:logoFile.type||"image/png",upsert:false});if(up.error)throw up.error;logoUrl=supabase.storage.from("admin-assets").getPublicUrl(path).data.publicUrl}if(editingLink){const upd=await supabase.from("important_links").update({title:form.title.trim(),url:form.url.trim(),logo_url:logoUrl}).eq("id",editingLink.id);if(upd.error)throw upd.error}else{const ins=await supabase.from("important_links").insert({title:form.title.trim(),url:form.url.trim(),logo_url:logoUrl});if(ins.error)throw ins.error}closeModal();await load()}catch(e){setMessage(e.message||"Link save failed")}finally{setUploadingLogo(false)}}
 function openEditLink(link){setMessage("");setEditingLink(link);setLogoFile(null);setForm({...emptyForm,title:link.title||"",url:link.url||"",logo_url:link.logo_url||""});setModal("link")}
 async function deleteLink(id){if(!window.confirm("Delete this link?"))return;const {error}=await supabase.from("important_links").delete().eq("id",id);if(error)setMessage(error.message);await load()}
 function openCreateStaff(){setMessage("");setEditingStaff(null);setStaffForm({full_name:"",email:"",password:"",permissions:permissionItems.reduce((a,[k])=>({...a,[k]:false}),{})});setModal("staff")}
 function openEditStaff(s){setMessage("");setEditingStaff(s);setStaffForm({full_name:s.full_name||"",email:s.email||"",password:"",permissions:{...permissionItems.reduce((a,[k])=>({...a,[k]:false}),{}),...(s.permissions||{})}});setModal("staff")}
 async function saveStaff(e){e.preventDefault();setMessage("");try{if(!editingStaff&&!staffForm.password){setMessage("Password is required for a new staff account.");return}const body=editingStaff?{action:"update_staff",user_id:editingStaff.id,full_name:staffForm.full_name.trim(),password:staffForm.password||undefined,permissions:staffForm.permissions}:{action:"create_staff",full_name:staffForm.full_name.trim(),email:staffForm.email.trim(),password:staffForm.password,permissions:staffForm.permissions};const {data,error}=await supabase.functions.invoke("admin-user-management",{body});if(error)throw new Error(error.message||"Staff save failed");if(data?.error)throw new Error(data.error);closeModal();await load()}catch(e){setMessage(e.message||"Staff save failed")}}
 async function deleteStaff(s){if(!window.confirm(`Delete staff account for ${s.full_name||s.email}?`))return;setMessage("");const {data,error}=await supabase.functions.invoke("admin-user-management",{body:{action:"delete_staff",user_id:s.id}});if(error||data?.error)setMessage(error?.message||data?.error||"Could not delete staff");else await load()}
 async function toggleStaff(s){const {data,error}=await supabase.functions.invoke("admin-user-management",{body:{action:"update_staff",user_id:s.id,full_name:s.full_name,permissions:s.permissions||{},disabled:!s.disabled}});if(error||data?.error)setMessage(error?.message||data?.error||"Could not update staff");else await load()}
 const PermissionBox=({name,label})=><label style={{display:"flex",alignItems:"center",gap:8,padding:"7px 0"}}><input type="checkbox" checked={!!staffForm.permissions[name]} onChange={e=>setStaffForm(f=>({...f,permissions:{...f.permissions,[name]:e.target.checked}}))}/><span>{label}</span></label>;
 return <div className="admin-shell"><header className="admin-top"><div className="admin-brand"><Shield size={22}/><div><b>PrintBhejo Admin</b><span>{isAdmin?"Control Panel":"Staff Control Panel"}</span></div></div><div className="admin-account"><span>{user?.email}</span><button onClick={onLogout} type="button"><LogOut size={17}/> Logout</button></div></header><main className="admin-main"><div className="admin-heading"><div><h1>Dashboard</h1><p>Analytics automatically refresh every 1 minute.</p></div><button className="refresh" onClick={load} disabled={refreshing} type="button"><RefreshCw size={17}/>{refreshing?"Updating…":"Refresh"}</button></div>{can("dashboard_view")&&<><section className="stat-grid"><Stat icon={<Users/>} label="Total Users" value={stats.users}/><Stat icon={<Shield/>} label="Total Logins" value={stats.logins}/><Stat icon={<BarChart3/>} label="Today's Logins" value={stats.todayLogins}/><Stat icon={<BarChart3/>} label="Total Transfers" value={stats.transfers}/><Stat icon={<BarChart3/>} label="Today's Transfers" value={stats.todayTransfers}/></section><section className="admin-card pb-visitor-card"><div className="card-head"><div><h2>Website Visitors</h2><small>Login aur without-login dono visitors</small></div><button onClick={load} type="button"><BarChart3 size={17}/> Refresh</button></div>{visitorError?<p className="form-error">Visitor data load nahi hua: {visitorError}</p>:<div className="pb-visitor-grid"><V label="Total Visits" value={visitor.total} icon={<Eye/>}/><V label="Today" value={visitor.today} icon={<BarChart3/>}/><V label="Logged-in" value={visitor.logged_in} icon={<Users/>}/><V label="Guest" value={visitor.guest} icon={<Eye/>}/><V label="Today Logged-in" value={visitor.today_logged_in} icon={<Users/>}/><V label="Today Guest" value={visitor.today_guest} icon={<Eye/>}/><V label="Unique Sessions" value={visitor.unique_sessions} icon={<Users/>}/><V label="Today Unique" value={visitor.today_unique_sessions} icon={<Users/>}/></div>}</section></>}
 <div className="admin-columns">{can("users_view")&&<section className="admin-card"><div className="card-head"><h2>User Management</h2>{can("users_create")&&<button onClick={()=>{setMessage("");setModal("user")}} type="button"><UserPlus size={17}/> Add User</button>}</div>{loading?<p>Loading…</p>:<div className="user-list">{users.map(p=><div className="user-row" key={p.id}><div><b>{p.full_name||"Unnamed user"}</b><small>{p.id.slice(0,8)}…</small></div><span className={p.disabled?"off":"on"}>{p.disabled?"Disabled":"Active"}</span>{can("users_qr")&&<button onClick={()=>prepareAndDownloadQr(p)} type="button" title={p.permanent_pin?"Download Permanent QR":"Generate & download Permanent QR"} disabled={actionUser===p.id}><QrCode size={16}/><span>QR</span></button>}{can("users_disable")&&<button onClick={()=>toggleUser(p)} type="button" disabled={actionUser===p.id}>{p.disabled?"Enable":"Disable"}</button>}{can("users_delete")&&<button onClick={()=>deleteUser(p)} type="button" title="Delete account" disabled={actionUser===p.id}><Trash2 size={16}/></button>}</div>)}{!users.length&&<p>No users yet.</p>}</div>}</section>}{can("links_manage")&&<section className="admin-card"><div className="card-head"><h2>Important Links</h2><button onClick={()=>{setMessage("");resetForm();setModal("link")}} type="button"><Plus size={17}/> Add Link</button></div><div className="link-list">{links.map(link=><div className="link-row" key={link.id}>{link.logo_url?<img src={link.logo_url} alt=""/>:<Link2/>}<div><b>{link.title}</b><small>{link.url}</small></div><button onClick={()=>openEditLink(link)} aria-label={`Edit ${link.title}`} title="Edit" type="button"><Pencil size={17}/></button><button onClick={()=>deleteLink(link.id)} aria-label={`Delete ${link.title}`} title="Delete" type="button"><Trash2 size={17}/></button></div>)}{!links.length&&<p>No links added.</p>}</div></section>}</div>
 {isAdmin&&<section className="admin-card" style={{marginTop:16}}><div className="card-head"><div><h2>Staff Management</h2><small>Create staff logins and choose exactly what they can handle.</small></div><button onClick={openCreateStaff} type="button"><UserPlus size={17}/> Add Staff</button></div><div className="user-list">{staff.map(s=><div className="user-row" key={s.id}><div><b>{s.full_name||"Unnamed staff"}</b><small>{s.email}</small></div><span className={s.disabled?"off":"on"}>{s.disabled?"Disabled":"Active"}</span><button onClick={()=>toggleStaff(s)} type="button">{s.disabled?"Enable":"Disable"}</button><button onClick={()=>openEditStaff(s)} type="button" title="Edit permissions"><Pencil size={16}/></button><button onClick={()=>deleteStaff(s)} type="button" title="Delete staff"><Trash2 size={16}/></button></div>)}{!staff.length&&<p>No staff accounts yet.</p>}</div></section>}
 </main>{modal&&<div className="modal-backdrop"><div className="admin-modal"><button className="modal-close" onClick={closeModal} aria-label="Close" type="button"><X/></button>{modal==="user"?<><h2>Create New User</h2><form onSubmit={createUser}><input required placeholder="User Name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><input required type="email" placeholder="Login ID / Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required minLength="6" type="password" placeholder="Password (6+ characters)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{message&&<p className="form-error">{message}</p>}<button className="admin-primary" type="submit">Create User</button></form></>:modal==="staff"?<><h2>{editingStaff?"Edit Staff Permissions":"Create Staff Login"}</h2><form onSubmit={saveStaff}><input required placeholder="Staff Name" value={staffForm.full_name} onChange={e=>setStaffForm({...staffForm,full_name:e.target.value})}/><input required={!editingStaff} disabled={!!editingStaff} type="email" placeholder="Login ID / Email" value={staffForm.email} onChange={e=>setStaffForm({...staffForm,email:e.target.value})}/><input required={!editingStaff} minLength="6" type="password" placeholder={editingStaff?"New Password (optional)":"Password (6+ characters)"} value={staffForm.password} onChange={e=>setStaffForm({...staffForm,password:e.target.value})}/><div style={{marginTop:12}}><b>Permissions</b>{permissionItems.map(([k,l])=><PermissionBox key={k} name={k} label={l}/>)}</div>{message&&<p className="form-error">{message}</p>}<button className="admin-primary" type="submit">{editingStaff?"Save Permissions":"Create Staff"}</button></form></>:<><h2>{editingLink?"Edit Important Link":"Add Important Link"}</h2><form onSubmit={saveLink}><input required placeholder="Link Name" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input required type="url" placeholder="https://example.com" value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/><input placeholder="Logo URL (optional)" value={form.logo_url} onChange={e=>setForm({...form,logo_url:e.target.value})}/><label style={{display:"block",marginTop:8,fontWeight:600}}>Or upload logo<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml,image/gif" onChange={e=>setLogoFile(e.target.files?.[0]||null)} style={{marginTop:6}}/></label>{logoFile&&<small style={{display:"block",marginTop:6}}>Selected: {logoFile.name}</small>}{message&&<p className="form-error">{message}</p>}<button className="admin-primary" type="submit" disabled={uploadingLogo}><Upload size={17}/>{uploadingLogo?"Uploading…":editingLink?"Save Changes":"Add Link"}</button></form></>}</div></div>}</div>}
function Stat({icon,label,value}){return <div className="stat-card"><div className="stat-icon">{icon}</div><span>{label}</span><strong>{Number(value||0).toLocaleString()}</strong></div>}
function V({icon,label,value}){return <div className="visitor-stat">{icon}<span>{label}</span><strong>{Number(value||0).toLocaleString()}</strong></div>}
