import React, { useEffect, useMemo, useState } from "react";
import { BarChart3, Eye, Link2, LogOut, Plus, RefreshCw, Shield, Trash2, UserPlus, Users, X, Upload } from "lucide-react";
import { supabase } from "./config";
import "./admin-ui.css";
import "./visitor-analytics.css";

const emptyForm = { full_name:"", email:"", password:"", title:"", url:"", logo_url:"" };
const initialVisitor = {total:0,today:0,logged_in:0,guest:0,today_logged_in:0,today_guest:0,unique_sessions:0,today_unique_sessions:0};

export default function AdminPanel({user,onLogout}){
 const [profiles,setProfiles]=useState([]),[links,setLinks]=useState([]),[stats,setStats]=useState({users:0,logins:0,transfers:0,todayLogins:0,todayTransfers:0}),[visitor,setVisitor]=useState(initialVisitor);
 const [loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[visitorError,setVisitorError]=useState(""),[modal,setModal]=useState(null),[message,setMessage]=useState(""),[form,setForm]=useState(emptyForm),[logoFile,setLogoFile]=useState(null),[uploadingLogo,setUploadingLogo]=useState(false);
 const load=async()=>{if(!supabase)return;setRefreshing(true);const start=new Date();start.setHours(0,0,0,0);const [p,l,lg,tr,tlg,ttr,v]=await Promise.all([
  supabase.from("profiles").select("id,full_name,role,disabled,created_at,last_login_at").order("created_at",{ascending:false}),
  supabase.from("important_links").select("*").order("created_at",{ascending:false}),
  supabase.from("login_events").select("id",{count:"exact",head:true}),
  supabase.from("transfer_events").select("id",{count:"exact",head:true}),
  supabase.from("login_events").select("id",{count:"exact",head:true}).gte("created_at",start.toISOString()),
  supabase.from("transfer_events").select("id",{count:"exact",head:true}).gte("created_at",start.toISOString()),
  supabase.rpc("get_visitor_stats")
 ]);setProfiles(p.data||[]);setLinks(l.data||[]);setStats({users:(p.data||[]).filter(x=>x.role==="user").length,logins:lg.count||0,transfers:tr.count||0,todayLogins:tlg.count||0,todayTransfers:ttr.count||0});if(v.error){setVisitorError(v.error.message)}else{setVisitor({...initialVisitor,...(v.data||{})});setVisitorError("")}setRefreshing(false);setLoading(false)};
 useEffect(()=>{load();const t=setInterval(load,60000);return()=>clearInterval(t)},[]);
 const users=useMemo(()=>profiles.filter(p=>p.role==="user"),[profiles]);
 const resetForm=()=>{setForm(emptyForm);setLogoFile(null)};
 const closeModal=()=>{setModal(null);setMessage("");resetForm()};
 async function createUser(e){e.preventDefault();setMessage("");try{const {data,error}=await supabase.functions.invoke("admin-user-management",{body:{action:"create",full_name:form.full_name.trim(),email:form.email.trim(),password:form.password}});if(error)throw new Error(error.message||"User create failed");if(data?.error)throw new Error(data.error);closeModal();await load()}catch(e){setMessage(e.message||"User create failed")}}
 async function toggleUser(profile){try{const {data,error}=await supabase.functions.invoke("admin-user-management",{body:{action:profile.disabled?"enable":"disable",user_id:profile.id}});if(error)throw new Error(error.message||"Could not update user");if(data?.error)throw new Error(data.error);await load()}catch(e){setMessage(e.message||"Could not update user")}}
 async function addLink(e){e.preventDefault();setMessage("");if(!form.title.trim()||!form.url.trim()){setMessage("Link name and website URL are required.");return}try{let logoUrl=form.logo_url.trim()||null;if(logoFile){setUploadingLogo(true);const ext=(logoFile.name.split(".").pop()||"png").toLowerCase().replace(/[^a-z0-9]/g,"");const path=`links/${crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from("admin-assets").upload(path,logoFile,{contentType:logoFile.type||"image/png",upsert:false});if(up.error)throw up.error;const pub=supabase.storage.from("admin-assets").getPublicUrl(path);logoUrl=pub.data.publicUrl}const ins=await supabase.from("important_links").insert({title:form.title.trim(),url:form.url.trim(),logo_url:logoUrl});if(ins.error)throw ins.error;closeModal();await load()}catch(e){setMessage(e.message||"Link add failed")}finally{setUploadingLogo(false)}}
 async function deleteLink(id){if(!window.confirm("Delete this link?"))return;const {error}=await supabase.from("important_links").delete().eq("id",id);if(error)setMessage(error.message);await load()}
 return <div className="admin-shell"><header className="admin-top"><div className="admin-brand"><Shield size={22}/><div><b>PrintBhejo Admin</b><span>Control Panel</span></div></div><div className="admin-account"><span>{user?.email}</span><button onClick={onLogout} type="button"><LogOut size={17}/> Logout</button></div></header>
 <main className="admin-main"><div className="admin-heading"><div><h1>Dashboard</h1><p>Analytics automatically refresh every 1 minute.</p></div><button className="refresh" onClick={load} disabled={refreshing} type="button"><RefreshCw size={17}/>{refreshing?"Updating…":"Refresh"}</button></div>
 <section className="stat-grid"><Stat icon={<Users/>} label="Total Users" value={stats.users}/><Stat icon={<Shield/>} label="Total Logins" value={stats.logins}/><Stat icon={<BarChart3/>} label="Today's Logins" value={stats.todayLogins}/><Stat icon={<BarChart3/>} label="Total Transfers" value={stats.transfers}/><Stat icon={<BarChart3/>} label="Today's Transfers" value={stats.todayTransfers}/></section>
 <section className="admin-card pb-visitor-card"><div className="card-head"><div><h2>Website Visitors</h2><small>Login aur without-login dono visitors</small></div><button onClick={load} type="button"><BarChart3 size={17}/> Refresh</button></div>{visitorError?<p className="form-error">Visitor data load nahi hua: {visitorError}</p>:<div className="pb-visitor-grid"><V label="Total Visits" value={visitor.total} icon={<Eye/>}/><V label="Today" value={visitor.today} icon={<BarChart3/>}/><V label="Logged-in" value={visitor.logged_in} icon={<Users/>}/><V label="Guest" value={visitor.guest} icon={<Eye/>}/><V label="Today Logged-in" value={visitor.today_logged_in} icon={<Users/>}/><V label="Today Guest" value={visitor.today_guest} icon={<Eye/>}/><V label="Unique Sessions" value={visitor.unique_sessions} icon={<Users/>}/><V label="Today Unique" value={visitor.today_unique_sessions} icon={<Users/>}/></div>}</section>
 <div className="admin-columns"><section className="admin-card"><div className="card-head"><h2>User Management</h2><button onClick={()=>{setMessage("");setModal("user")}} type="button"><UserPlus size={17}/> Add User</button></div>{loading?<p>Loading…</p>:<div className="user-list">{users.map(p=><div className="user-row" key={p.id}><div><b>{p.full_name||"Unnamed user"}</b><small>{p.id.slice(0,8)}…</small></div><span className={p.disabled?"off":"on"}>{p.disabled?"Disabled":"Active"}</span><button onClick={()=>toggleUser(p)} type="button">{p.disabled?"Enable":"Disable"}</button></div>)}{!users.length&&<p>No users yet.</p>}</div>}</section>
 <section className="admin-card"><div className="card-head"><h2>Important Links</h2><button onClick={()=>{setMessage("");setModal("link")}} type="button"><Plus size={17}/> Add Link</button></div><div className="link-list">{links.map(link=><div className="link-row" key={link.id}>{link.logo_url?<img src={link.logo_url} alt=""/>:<Link2/>}<div><b>{link.title}</b><small>{link.url}</small></div><button onClick={()=>deleteLink(link.id)} aria-label="Delete" type="button"><Trash2 size={17}/></button></div>)}{!links.length&&<p>No links added.</p>}</div></section></div></main>
 {modal&&<div className="modal-backdrop"><div className="admin-modal"><button className="modal-close" onClick={closeModal} aria-label="Close" type="button"><X/></button>{modal==="user"?<><h2>Create New User</h2><form onSubmit={createUser}><input required placeholder="User Name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><input required type="email" placeholder="Login ID / Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required minLength="6" type="password" placeholder="Password (6+ characters)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{message&&<p className="form-error">{message}</p>}<button className="admin-primary" type="submit">Create User</button></form></>:<><h2>Add Important Link</h2><form onSubmit={addLink}><input required placeholder="Link Name" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input required type="url" placeholder="https://example.com" value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/><input placeholder="Logo URL (optional)" value={form.logo_url} onChange={e=>setForm({...form,logo_url:e.target.value})}/><label style={{display:"block",marginTop:8,fontWeight:600}}>Or upload logo<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml,image/gif" onChange={e=>setLogoFile(e.target.files?.[0]||null)} style={{marginTop:6}}/></label>{logoFile&&<small style={{display:"block",marginTop:6}}>Selected: {logoFile.name}</small>}{message&&<p className="form-error">{message}</p>}<button className="admin-primary" type="submit" disabled={uploadingLogo}><Upload size={17}/>{uploadingLogo?"Uploading…":"Add Link"}</button></form></>}</div></div>}</div>
}
function Stat({icon,label,value}){return <div className="stat-card"><div className="stat-icon">{icon}</div><span>{label}</span><strong>{Number(value||0).toLocaleString()}</strong></div>}
function V({icon,label,value}){return <div className="visitor-stat">{icon}<span>{label}</span><strong>{Number(value||0).toLocaleString()}</strong></div>}
