import "./qr-polyfill";
import React,{Component,useEffect} from "react";
import {createRoot} from "react-dom/client";
import App from "./App";
import RoleGate from "./RoleGate";
import LoginTracker from "./LoginTracker";
import "./styles.css";
import "./ui-overrides.css";
import "./scroll-fix.css";
import "./batch-ui.css";
import "./converter-tools.css";
import "./free-tools-replacement.css";
import "./free-tools-placement.css";
import "./visitor-analytics.css";
import "./live-links.css";
class AppErrorBoundary extends Component{state={error:null};static getDerivedStateFromError(error){return{error}}componentDidCatch(error,info){console.error("PrintBhejo runtime error:",error,info)}render(){if(!this.state.error)return this.props.children;return <div style={{minHeight:"100vh",display:"grid",placeItems:"center",padding:24,fontFamily:"system-ui,sans-serif",background:"#f6f8fc",color:"#111827"}}><div style={{maxWidth:520,width:"100%",background:"#fff",borderRadius:20,padding:24,boxShadow:"0 12px 40px rgba(0,0,0,.10)"}}><h2>PrintBhejo couldn't load</h2><p>A browser-side error occurred.</p><pre style={{whiteSpace:"pre-wrap",wordBreak:"break-word",fontSize:12,background:"#f3f4f6",padding:12,borderRadius:12,overflow:"auto"}}>{String(this.state.error?.message||this.state.error)}</pre><button onClick={()=>window.location.reload()}>Reload PrintBhejo</button></div></div>}}
let converterRoot=null,converterMounting=false,linksRoot=null,linksMounting=false;
async function mountModernConverter(){if(converterMounting)return;const linksSection=Array.from(document.querySelectorAll("section")).find(s=>/important\s+links/i.test(s.textContent||""));if(!linksSection)return;let slot=document.querySelector(".converter-tools-slot");if(!slot){slot=document.createElement("div");slot.className="converter-tools-slot";linksSection.parentNode?.insertBefore(slot,linksSection)}if(converterRoot)return;converterMounting=true;try{const mod=await import("./ConverterTools.jsx");converterRoot=createRoot(slot);converterRoot.render(<mod.default inline/>)}catch(error){console.error("PrintBhejo converter tools failed to load:",error);slot.remove()}finally{converterMounting=false}}
async function mountLiveLinks(){if(linksMounting||linksRoot)return;const section=Array.from(document.querySelectorAll("section")).find(s=>/important\s+links/i.test(s.textContent||""));if(!section)return;let slot=section.querySelector(".pb-live-links-slot");if(!slot){slot=document.createElement("div");slot.className="pb-live-links-slot";section.appendChild(slot)}linksMounting=true;try{const mod=await import("./ImportantLinksLive.jsx");linksRoot=createRoot(slot);linksRoot.render(<mod.default/>)}catch(error){console.error("PrintBhejo live links failed:",error);slot.remove()}finally{linksMounting=false}}
function downloadPermanentQr(img,pin){try{fetch(img.src,{mode:"cors",cache:"no-store"}).then(r=>r.blob()).then(blob=>{const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`PrintBhejo-Permanent-QR-${pin}.png`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}).catch(()=>{const a=document.createElement("a");a.href=img.src;a.target="_blank";a.rel="noopener";a.click()})}catch{}}
function enhancePermanentQrUI(){const loggedIn=document.body.classList.contains("pb-authenticated"),panel=document.querySelector(".pin-panel"),img=panel?.querySelector(".qr-code");if(!panel||!img)return;const expiry=panel.querySelector(".expiry"),strong=Array.from(panel.querySelectorAll("strong")).find(el=>/Receiver PIN auto-generated/i.test(el.textContent||""));let btn=panel.querySelector(".pb-download-qr");if(loggedIn){if(expiry)expiry.style.display="none";if(strong)strong.textContent="Permanent PIN • QR code stays active with your account";const note=panel.querySelector(".qr-wrap span");if(note)note.textContent="Permanent QR • sender scan karke connect kar sakta hai";if(!btn){btn=document.createElement("button");btn.type="button";btn.className="secondary pb-download-qr";btn.textContent="Download Permanent QR";btn.onclick=()=>downloadPermanentQr(img,img.alt.match(/[A-Z0-9]{4}$/)?.[0]||"PIN");panel.querySelector("button")?.after(btn)}}else{if(expiry)expiry.style.display="";if(strong)strong.textContent="Receiver PIN auto-generated • Sender PIN enter ya QR scan kare";btn?.remove()}}
function enhanceTransferUI(){const tabs=document.querySelector(".tabs");if(tabs){const bs=Array.from(tabs.querySelectorAll("button")),send=bs.find(b=>/send/i.test(b.textContent||"")),receive=bs.find(b=>/receive/i.test(b.textContent||""));if(send&&receive){const loggedIn=document.body.classList.contains("pb-authenticated");send.style.order=loggedIn?"2":"1";receive.style.order=loggedIn?"1":"2"}}const uploadArea=document.querySelector(".upload-area");if(uploadArea){const success=document.querySelector(".notice")?.textContent?.includes("Files sent successfully");if(success&&!uploadArea.querySelector(".pb-send-again")){document.querySelectorAll(".selected-list .selected > button").forEach(btn=>btn.click());const btn=document.createElement("button");btn.className="secondary pb-send-again";btn.type="button";btn.textContent="＋ Send Another File";btn.onclick=()=>{const input=uploadArea.querySelector('.dropzone input[type="file"]');if(input){input.value="";input.click()}};uploadArea.appendChild(btn)}}enhancePermanentQrUI();mountModernConverter();mountLiveLinks()}
function Root(){useEffect(()=>{const observer=new MutationObserver(()=>{clearTimeout(window.__pbEnhanceTimer);window.__pbEnhanceTimer=setTimeout(enhanceTransferUI,50)});observer.observe(document.body,{childList:true,subtree:true});enhanceTransferUI();return()=>{observer.disconnect();clearTimeout(window.__pbEnhanceTimer);converterRoot?.unmount?.();converterRoot=null;linksRoot?.unmount?.();linksRoot=null}},[]);return <><LoginTracker/><RoleGate><App/></RoleGate></>}
createRoot(document.getElementById("root")).render(<AppErrorBoundary><Root/></AppErrorBoundary>);
